version: 5.1.0
variant: default
logo: /img/logo.png
head:
    favicon: /img/favicon.png
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - 'name=referrer;content=no-referrer'
    rss: /atom.xml
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/xiaohuiluo/
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        # Download on GitHub:
        #     icon: fab fa-github
        #     url: https://github.com/ppoffice/hexo-theme-icarus
article:
    highlight:
        theme: vs
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
    index_pages: true
comment:
    type: changyan
    app_id: 'cywpxBL0d'
    conf: 'prod_ccdfddbc3432d3184fac703760a8e1f4'
# donates:
#     -
#         type: afdian
#         url: ''
#     -
#         type: alipay
#         qrcode: ''
#     -
#         type: buymeacoffee
#         url: ''
#     -
#         type: patreon
#         url: ''
#     -
#         type: paypal
#         business: ''
#         currency_code: USD
#     -
#         type: wechat
#         qrcode: ''
share:
    type: addtoany
    # install_url: ''
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: HUI
        author_title: 好好学习,天天向上
        location: Shenzhen
        avatar: 
        avatar_rounded: true
        gravatar: 
        follow_link: https://github.com/xiaohuiluo
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/xiaohuiluo
            # Facebook:
            #     icon: fab fa-facebook
            #     url: https://facebook.com
            # Twitter:
            #     icon: fab fa-twitter
            #     url: https://twitter.com
            # Dribbble:
            #     icon: fab fa-dribbble
            #     url: https://dribbble.com
            RSS:
                icon: fas fa-rss
                url: /atom.xml
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    # -
        # position: left
        # type: links
        # links:
        #     Hexo: https://hexo.io
        #     Bulma: https://bulma.io
    -
        position: left
        type: categories
    -
        position: left
        type: recent_posts
    -
        position: left
        type: archives
    -
        position: left
        type: tags
        order_by: name
        amount: 
        show_count: true
    -
        position: left
        type: subscribe_email
        description: 
        feedburner_id: ''
    # -
        # position: left
        # type: adsense
        # client_id: ''
        # slot_id: ''
    # -
        # position: left
        # type: followit
        # description: 
        # action_url: ''
        # verification_code: ''
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: true
    cnzz:
        id: 
        web_id: 
    # cookie_consent:
    #     type: info
    #     theme: edgeless
    #     static: false
    #     position: bottom-left
    #     policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: true
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: 'https://cdn.bootcdn.net/ajax/libs/font-awesome/6.2.1/css/all.min.css'
